# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('illustration', models.ImageField(upload_to='/Users/patsykakaz_LSC/Documents/PRO/BGRACE/MAIN/static/media/boat/illustration')),
                ('logo_boat', models.ImageField(upload_to='/Users/patsykakaz_LSC/Documents/PRO/BGRACE/MAIN/static/media/boat/logo_boat')),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation', models.TextField(blank=True, null=True)),
                ('architecte', models.CharField(blank=True, max_length=255, null=True)),
                ('longeur_HT', models.CharField(blank=True, max_length=255, null=True)),
                ('longueur_coque', models.CharField(blank=True, max_length=255, null=True)),
                ('largeur', models.CharField(blank=True, max_length=255, null=True)),
                ('tirant_eau', models.CharField(blank=True, max_length=255, null=True)),
                ('deplacement', models.CharField(blank=True, max_length=255, null=True)),
                ('leste', models.CharField(blank=True, max_length=255, null=True)),
                ('surface_voile', models.CharField(blank=True, max_length=255, null=True)),
                ('spi', models.CharField(blank=True, max_length=255, null=True)),
                ('motorisation', models.CharField(blank=True, max_length=255, null=True)),
                ('capacite_carburant', models.CharField(blank=True, max_length=255, null=True)),
                ('capacite_eau', models.CharField(blank=True, max_length=255, null=True)),
                ('cabines', models.CharField(blank=True, max_length=255, null=True)),
                ('certification_CE', models.CharField(blank=True, max_length=255, null=True)),
                ('association_classe', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
    ]
