# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('headline', models.CharField(blank=True, max_length=255, null=True)),
                ('illustration', models.ImageField(upload_to='/Users/patsykakaz_LSC/Documents/PRO/BGRACE/MAIN/static/media/boat/illustration')),
                ('logo_boat', models.ImageField(upload_to='/Users/patsykakaz_LSC/Documents/PRO/BGRACE/MAIN/static/media/boat/logo_boat')),
                ('documentation', models.FileField(upload_to='boat/doc/')),
                ('presentation', mezzanine.core.fields.RichTextField(verbose_name='Presentation')),
                ('architecte', models.CharField(blank=True, max_length=255, null=True)),
                ('longueur_HT', models.CharField(blank=True, max_length=255, null=True)),
                ('longueur_coque', models.CharField(blank=True, max_length=255, null=True)),
                ('largeur', models.CharField(blank=True, max_length=255, null=True)),
                ('tirant_eau', models.CharField(blank=True, max_length=255, null=True)),
                ('deplacement', models.CharField(blank=True, max_length=255, null=True)),
                ('leste', models.CharField(blank=True, max_length=255, null=True)),
                ('surface_voile', models.CharField(blank=True, max_length=255, null=True)),
                ('spi', models.CharField(blank=True, max_length=255, null=True)),
                ('motorisation', models.CharField(blank=True, max_length=255, null=True)),
                ('capacite_carburant', models.CharField(blank=True, max_length=255, null=True)),
                ('capacite_eau', models.CharField(blank=True, max_length=255, null=True)),
                ('cabines', models.CharField(blank=True, max_length=255, null=True)),
                ('certification_CE', models.CharField(blank=True, max_length=255, null=True)),
                ('association_classe', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='BoatDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileTarget', models.FileField(upload_to='boat/doc/')),
                ('doc_nature', models.CharField(choices=[('', ''), ('Pr\xe9sentation', 'Pr\xe9sentation'), ('VPP', 'VPP'), ('Courbe de stabilit\xe9 ', 'Courbe de stabilit\xe9 '), ('R\xe8gle de classe ', 'R\xe8gle de classe '), ('Caract\xe9ristiques techniques d\xe9taill\xe9es ', 'Caract\xe9ristiques techniques d\xe9taill\xe9es '), ('Plan d\u2019am\xe9nagement', 'Plan d\u2019am\xe9nagement'), ('Options', 'Options')], default='', max_length=50)),
                ('alternative_doc_nature', models.CharField(blank=True, max_length=255, null=True)),
                ('Boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.Boat')),
            ],
        ),
        migrations.CreateModel(
            name='BoatPalmares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('course', models.CharField(max_length=255)),
                ('resultat', models.CharField(max_length=255)),
                ('Boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.Boat')),
            ],
        ),
    ]
