# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatPalmares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('course', models.CharField(max_length=255)),
                ('resultat', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='boat',
            old_name='longeur_HT',
            new_name='longueur_HT',
        ),
        migrations.AddField(
            model_name='boat',
            name='documentation',
            field=models.FileField(default=False, upload_to='boat/doc/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boat',
            name='presentation',
            field=mezzanine.core.fields.RichTextField(default=False, verbose_name='Presentation'),
            preserve_default=False,
        ),
    ]
