# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_auto_20160128_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatDocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileTarget', models.FileField(upload_to='boat/doc/')),
                ('doc_nature', models.CharField(choices=[('', ''), ('Pr\xe9sentation', 'Pr\xe9sentation'), ('VPP', 'VPP'), ('Courbe de stabilit\xe9 ', 'Courbe de stabilit\xe9 '), ('R\xe8gle de classe ', 'R\xe8gle de classe '), ('Caract\xe9ristiques techniques d\xe9taill\xe9es ', 'Caract\xe9ristiques techniques d\xe9taill\xe9es '), ('Plan d\u2019am\xe9nagement', 'Plan d\u2019am\xe9nagement'), ('Options', 'Options')], default='', max_length=50)),
                ('alternative_doc_nature', models.CharField(blank=True, max_length=255, null=True)),
                ('Boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.Boat')),
            ],
        ),
        migrations.AddField(
            model_name='boatpalmares',
            name='Boat',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='MAIN.Boat'),
            preserve_default=False,
        ),
    ]
