# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0002_auto_20160201_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
