# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_boat_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='documentation',
        ),
    ]
