# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_remove_boat_documentation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='highlight',
            field=models.NullBooleanField(default=False),
        ),
    ]
