# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_auto_20160202_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='/Users/patsykakaz_LSC/Documents/PRO/BGRACE/MAIN/static/media/boat/logo_boat'),
        ),
    ]
