# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_auto_20160202_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='illustration',
            new_name='featured_image',
        ),
    ]
