# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 09:19
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_auto_20160202_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='featured_image',
            field=filebrowser.fields.FileBrowseField(max_length=255, verbose_name='Image'),
        ),
    ]
