# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 09:26
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0008_auto_20160203_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='featured_image',
            field=mezzanine.core.fields.FileField(max_length=255, null=True, verbose_name='Featured Image'),
        ),
    ]
