# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0010_auto_20160203_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', mezzanine.core.fields.FileField(max_length=255, null=True, verbose_name='Image')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='boat',
            name='sidecut_image',
            field=mezzanine.core.fields.FileField(max_length=255, null=True, verbose_name='Plan Coupe'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='featured_image',
            field=mezzanine.core.fields.FileField(max_length=255, null=True, verbose_name='Image en Situation'),
        ),
        migrations.AlterField(
            model_name='boat',
            name='logo',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Logo Bateau'),
        ),
        migrations.AddField(
            model_name='boatgalery',
            name='Boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.Boat'),
        ),
    ]
