# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0011_auto_20160203_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boatgalery',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
