# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0012_auto_20160203_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boat',
            old_name='headline',
            new_name='baseline',
        ),
    ]
