# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0013_auto_20160205_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='baseline_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='baseline_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='boat',
            name='presentation_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Presentation'),
        ),
        migrations.AddField(
            model_name='boat',
            name='presentation_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Presentation'),
        ),
        migrations.AddField(
            model_name='distributeur',
            name='presentation_en',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Presentation'),
        ),
        migrations.AddField(
            model_name='distributeur',
            name='presentation_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Presentation'),
        ),
    ]
