# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 18:05
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0014_auto_20160208_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='sidecut_image_2',
            field=mezzanine.core.fields.FileField(max_length=255, null=True, verbose_name='Plan Coupe'),
        ),
    ]
